estante/urls.py
from django.conf.urls import url
from estante import views
from estante.views import *
from django.views.generic.base import TemplateView


urlpatterns = [
    url(r'^$', Login.as_view(), name='login'),
    url(r'^cad_pessoa/$', CadastraPessoa.as_view(), name='cadastro-pessoa'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'/estante'}, name='logout'),
    url(r'^cad_livro/$', CadastraLivro.as_view(), name='cadastro-livro'),
    url(r'^cad_livro/(?P<id>\d+)/$', CadastraLivro.as_view(), name='edita-livro'),
    url(r'^desativar/$', Alterar_status.as_view(), name='desativar'),
    url(r'^esconder/(?P<id>\d+)/$', Alterar_status_livro.as_view(), name='esconder_livro'),
    url(r'^ativar/$', Alterar_status.as_view(), name='ativar'),
    url(r'^perfil/$', TemplateView.as_view(template_name='perfil.html'), name='perfil'),
    url(r'^editar_perfil/$', CadastraPessoa.as_view(), name='editar_perfil'),
    url(r'^lista_livros/$', DicLivro.as_view(), name='lista_livros'),
    url(r'^livro/(?P<id>\w+)/$', PerfilLivro.as_view(), name='perfil_livro'),
    url(r'^emprestimo/(?P<id>\w+)/$', Cad_emprestimo.as_view(), name='emprestimo'),
    url(r'^procurar/$', Procurar.as_view(), name='procurar_livro'),
    url(r'^devolver/(?P<id>\w+)/$', views.Devolver, name='devolver_livro'),
    url(r'', TemplateView.as_view(template_name='404.html'), name='404'),
]

projeto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^estante/', include('estante.urls', namespace="estante")),
    # url(r'^$', views.index, name='index'),
]

estante/forms/livro.py
# coding=utf-8


from estante.forms.validators.livro_validator import *
from django import forms
from estante.models import Livro


class LivroForm(forms.ModelForm):
    id_livro = forms.IntegerField(label='ISBN')
    titulo = forms.CharField(max_length=50, label='Título')
    autor = forms.CharField(max_length=50, label='Autor')
    editora = forms.CharField(max_length=50, label='Editora')
    ano = forms.IntegerField(label='Ano')

    class Meta:
        model = Livro
        fields = "__all__"
        exclude = ("dono",)

    def clean_status(self):
        status = True
        return status

    def clean_id_livro(self):
        id_livro = self.cleaned_data['id_livro']
        livro =Livro.objects.filter(id_livro__contains=id_livro).exists()
        if livro:
            raise forms.ValidationError('ISBN já utilizado')
        if len(str(id_livro)) !=13:
            raise forms.ValidationError('ISBN precisa de 13 digitos')
        else:
            return id_livro

    def clean_ano(self):
        return AnoValidator(self.cleaned_data['ano'])


class LivroEditaForm(forms.ModelForm ):
    titulo = forms.CharField(max_length=50, label='Título')
    autor = forms.CharField(max_length=50, label='Autor')
    editora = forms.CharField(max_length=50, label='Editora')
    ano = forms.IntegerField(label='Ano')

    class Meta:
        model = Livro
        fields = "__all__"
        exclude = ("dono","id_livro",)

    def clean_status(self):
        status = True
        return status

    def clean_ano(self):
        return AnoValidator(self.cleaned_data['ano'])

estante/forms/pessoa.py
# coding=utf-8


from estante.forms.validators.pessoa_validator import *
from estante.models import Pessoa
from django import forms
from django.contrib.auth import authenticate


class PessoaForm(forms.ModelForm):
    cpf = forms.CharField(label='CPF')
    endereco = forms.CharField(max_length=30, label='Endereço')
    telefone = forms.IntegerField(label='Telefone')
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Pessoa
        fields = "__all__"
        exclude = ['date_joined']

    def clean_cpf(self):
        return CpfValidator(self.cleaned_data[str('cpf')])

    def clean_username(self):
        username=self.cleaned_data['username']
        if Pessoa.objects.filter(username=username).exists():
            raise forms.ValidationError('Usuário já existe')
        return username

    def clean_first_name(self):
        return NameValidator(self.cleaned_data['first_name'])

    def clean_last_name(self):
        return NameValidator(self.cleaned_data['last_name'])

class PessoaEditForm(forms.ModelForm):
    cpf = forms.IntegerField(label='CPF')
    endereco = forms.CharField(max_length=30, label='Endereço')
    telefone = forms.IntegerField(label='Telefone')
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Pessoa
        fields = "__all__"
        exclude = ['date_joined', 'username', 'is_active']

    def clean_cpf(self):
        return CpfValidator(self.cleaned_data[str('cpf')])

    def clean_first_name(self):
        return NameValidator(self.cleaned_data['first_name'])

    def clean_last_name(self):
        return NameValidator(self.cleaned_data['last_name'])

class LoginForm(forms.ModelForm):

    username = forms.CharField(max_length=254)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Pessoa
        fields = ('password', 'username',)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if Pessoa.objects.filter(username = username).exists():
            username = Pessoa.objects.get(username=username)
            if authenticate(username=username, password=password) == None:
                raise forms.ValidationError(("Usuario ou senha incorretos"))
        return self.cleaned_data

    def clean_username(self):
        return UsernameValidator(self.cleaned_data['username'])

estante/views/emprestimo.py
from django.views.generic import View
from estante.models.emprestimo import Emprestimo
from estante.models.livro import Livro
from estante.models.pessoa import Pessoa
from django.shortcuts import render
from datetime import date
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class Cad_emprestimo(View):

    @method_decorator(login_required(login_url='/estante/'))
    def get(self, request, id=None):
        livro = Livro.objects.get(pk=id)
        pessoa = Pessoa.objects.get(pk=request.user.id)
        emprestimo = Emprestimo()
        emprestimo.dt_emprest = date.today()
        emprestimo.dt_devol = date.fromordinal(date.today().toordinal() + 15)
        emprestimo.livro_emprestado = livro
        emprestimo.pegou_emprestado = pessoa

        emprestimo.save()

        livro.status = False
        livro.save()

        return render(request, 'perfil.html')


@method_decorator(login_required(login_url='/estante/'))
def Devolver(request, id=None):
    emprestimo = Emprestimo.objects.get(pk=id)
    livro = Livro.objects.get(pk=emprestimo.livro_emprestado_id)

    livro.status = True
    livro.save()

    emprestimo.delete()

    return render(request, 'perfil.html')

estante/views/livro.py
#coding=utf-8
from estante.models import Pessoa
from django.views.generic import View
from django.shortcuts import render, redirect
from estante.models.livro import Livro
from estante.models.emprestimo import Emprestimo
from estante.forms.livro import LivroForm, LivroEditaForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class DicLivro(View):
    template = 'lista_livros.html'

    @method_decorator(login_required(login_url='/estante/'))
    def get(self, request):
        context_dict = {}
        livros = Livro.objects.all()
        context_dict['livros'] = livros
        emprestimos = []
        for livro in livros:
            emprestimo = Emprestimo.objects.filter(livro_emprestado_id=livro.id).all()
            if emprestimo:
                emprestimos += emprestimo
        context_dict['emprestimos'] = emprestimos
        return render(request, self.template, context_dict)

class PerfilLivro(View):

    template = 'perfil_livro.html'

    @method_decorator(login_required(login_url='/estante/'))
    def get(self, request, id=None):
        livro = Livro.objects.get(pk=id)
        context_dict = {}
        emprestimo = Emprestimo.objects.filter(livro_emprestado_id=livro.id)
        if emprestimo:
            context_dict['emprestimo'] = emprestimo[0]
        context_dict['livro'] = livro
        return render(request, self.template, context_dict)


class CadastraLivro(View, Pessoa):

    template = 'cad_livro.html'

    @method_decorator(login_required(login_url='/estante/'))
    def get(self, request, id=None):

        if id:
            livro = Livro.objects.get(id=id)
            form = LivroEditaForm(instance=livro)
        else:
            form = LivroForm()
        return render(request, self.template, {'form': form, 'id': id})

    def post(self, request, id=None):
        if id:
            form = LivroEditaForm(request.POST, instance=Livro.objects.get(id=id))
            if form.is_valid():
                form.save()
                return redirect('/estante/lista_livros/')
            else:
                return render(request, self.template, {'form': form, 'id': id})

        else:
            form = LivroForm(request.POST)
            if form.is_valid():
                livro = form.save(commit=False)
                livro.dono = Pessoa.objects.get(pk=request.user.id)
                livro.status = True
                livro.save()

            msg = 'Livro cadastrado com sucesso!'
            form_limpo = LivroForm()
        return render(request, self.template, {'msg': msg, 'form': form_limpo})

class Alterar_status_livro(View):

    template = 'perfil_livro.html'

    @method_decorator(login_required(login_url='/estante/'))
    def post(self, request, id=None):
        user = request.user
        if user.is_authenticated():
            livro = Livro.objects.get(pk=id)
            if livro.status == False:
                livro.status = True
                livro.save()
                return redirect('/estante/livro/' + str(livro.id))
            else:
                livro.status = False
                livro.save()
                return redirect('/estante/livro/' + str(livro.id))
        return render(request, 'index.html')

class Procurar(View):

    template = 'procurar_livro.html'

    def get(self,request):
        return render(request, self.template, {'msg':'Nenhum livro encontrado!'})

    @method_decorator(login_required(login_url='/estante/'))
    def post(self, request):
        livros = {}
        msg = 'Nenhum livro encontrado!'
        tipo_lista = ''
        valor = request.POST['tipo']
        if valor == "titulo":
            titulo = request.POST['procura']
            tipo_lista = "lista"
            livros = Livro.objects.filter(titulo__icontains=titulo)
            if livros:
                msg = "Livros encontrados"

        elif valor == "autor":
            autor = request.POST['procura']
            tipo_lista = "lista"
            livros = Livro.objects.filter(autor__icontains=autor)
            if livros:
                msg = 'Autor Encontrado'

        elif valor == "dono":
            dono = request.POST['procura']
            tipo_lista = "dicionario"
            lista_donos = Pessoa.objects.filter(first_name__icontains=dono)
            print (lista_donos)
            if lista_donos:  # existe donos
                for dono in lista_donos:
                    livros[str(dono.id)] = Livro.objects.filter(dono=dono)
                if len(livros) == 0:
                    msg = "Nenhum livro encontrado!"
                else:
                    msg ="Dono encontrado"
            else:
                msg = "Dono não encontrado"

        return render(request, self.template, {'livros': livros, 'msg': msg,
                                               'tipo_lista': tipo_lista})

estante/views/pessoa.py
# coding=utf-8
from django.views.generic import View
from django.shortcuts import redirect
from estante.models.pessoa import Pessoa
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, render_to_response
from estante.forms.pessoa import PessoaForm, PessoaEditForm, LoginForm
from django.core.exceptions import ObjectDoesNotExist


class CadastraPessoa(View):
    template = 'cad_pessoa.html'
    template2 = 'perfil.html'
    template3 = 'index.html'

    def get(self, request):
        id = request.user.id
        if id:
            pessoa = Pessoa.objects.get(pk=id)
            form = PessoaEditForm(instance=pessoa)
        else:
            form = PessoaForm()
        return render(request, self.template, {'form': form})

    def post(self, request):
        id = request.user.id
        if id:
            pessoa = Pessoa.objects.get(pk=id)
            form = PessoaEditForm(instance=pessoa, data=request.POST)
            print (form)
            if form.is_valid():
                form = form.save(commit=False)
                form.set_password(request.POST['password'])
                form.is_active = True
                form.save()
                user = authenticate(username=pessoa.username, password=request.POST['password'])
                login(request, user)

                request.session['first_name'] = pessoa.first_name
                request.session['last_name'] = pessoa.last_name
                request.session['cpf'] = pessoa.cpf
                request.session['endereco'] = pessoa.endereco
                request.session['telefone'] = pessoa.telefone
                request.session['email'] = pessoa.email
                request.session['first_name'] = pessoa.first_name
                request.session.set_expiry(6000)
                request.session.get_expire_at_browser_close()

                return render(request, self.template2, {'msg': 'Informações alteradas com sucesso!'})
            else:
                print(form.errors)
            return render(request, self.template, {'form': form})
        else:
            form = PessoaForm(data=request.POST)
            if form.is_valid():
                pessoa = form.save(commit=False)
                pessoa.set_password(request.POST['password'])
                pessoa.is_active = True
                pessoa.save()

                return render(request, self.template3, {'form': LoginForm})
        return render(request, self.template, {'form': form})


class Login(View):
    template = 'index.html'
    template2 = 'perfil.html'
    template3 = 'alterar_status.html'

    def get(self, request):
        form = LoginForm()

        return render(request, self.template, {'form': form})

    def post(self, request):
        username = request.POST['username']
        try:
            form = LoginForm(data=request.POST, instance=Pessoa.objects.get(username=username))
        except ObjectDoesNotExist:
            form = LoginForm(data=request.POST)
        if form.is_valid() == False:
            return render(request, self.template, {'form': form})
        username = form.save(commit = False).username
        password = form.save(commit = False).password

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            pessoa = LoginForm(data=request.POST, instance=Pessoa.objects.get(username=username))
            id = request.user.id
            desativo = Pessoa.objects.get(pk=id)
            if desativo.is_active is False:
                logout(request)
                return render(request, self.template3, {'msg': 'Este usuario está inativo, deseja ativar?', 'form': LoginForm})
            if pessoa.is_valid():
                pessoa = pessoa.save(commit=False)
                request.session['first_name'] = pessoa.first_name
                request.session['last_name'] = pessoa.last_name
                request.session['cpf'] = pessoa.cpf
                request.session['endereco'] = pessoa.endereco
                request.session['telefone'] = pessoa.telefone
                request.session['email'] = pessoa.email
                request.session['first_name'] = pessoa.first_name
                request.session.set_expiry(6000)
                request.session.get_expire_at_browser_close()
                return render(request, self.template2, {'msg': 'Login efetuado com sucesso!'})
        else:
            return render(request, self.template, {'form': LoginForm})

class Alterar_status(View):
    template = 'alterar_status.html'
    template2 = 'index.html'

    def get(self, request):
        return render(request, self.template, {'form':LoginForm})

    def post(self, request):
        if request.user.id:
            ativo = Pessoa.objects.get(username=request.user)
            ativo.is_active = False
            ativo.save()
            logout(request)
            return redirect('/estante/')
        else:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                ativo = Pessoa.objects.get(username=user)
                if ativo.is_active is False:
                    ativo.is_active = True
                    ativo.save()
                    return render(request, self.template2, {'msg': 'usuario ativado com sucesso!','form':LoginForm})
                else:
                    return render(request, self.template, {'msg': 'Este usuario já esta ativo','form':LoginForm})
            else:
                return render(request, self.template, {'msg': 'Usuario ou senha incorretos','form':LoginForm})

estante/templates/alterar_status.html
{% extends 'base.html' %}
{% block content %}
     <form method="POST" action="{% url 'estante:ativar' %}" class='ui form'>

         {% if msg %}
            <p>{{ msg }}</p>
         {% endif %}

         <h4>Ativar usuário inativo</h4>

         {% csrf_token %}

         {% if form.username.errors %}
            {{ form.username.errors }}
         {% endif %}
         <label>{{ form.username.label }}</label>
         {{ form.username }} </br>

         {% if form.password.errors %}
             {{ form.password.errors }}
         {% endif %}
         <label>{{ form.password.label }}</label>
         {{ form.password }} </br>

         <button type="submit" class="ui verde button">Ativar</button><br>
         <a href="{% url 'estante:login' %}">Voltar ao index</a>
    </form>
{% endblock content %}

estante/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'semantic/dist/semantic.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'semantic/dist/semantic.min.css' %}">
    <script
 	 src="https://code.jquery.com/jquery-3.1.1.min.js"
 	 integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
 	 crossorigin="anonymous">
    </script>
    <script src="{% static 'semantic/dist/semantic.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'semantic/dist/semantic.js' %}"></script>
    <link rel="icon" href="{% static 'book-icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Bibliotefast</title>
</head>

<header>

    <div class="ui left vertical inverted thin sidebar menu visible" style="background-color: #120a18">
        <div class="item" id="logo_menu">
            <a class="ui logo icon image" href="/">
                <img src="{% static 'iconelivro.png' %}">
            </a>
            <br/><br/>
        </div>
        {% if user.is_authenticated %}
            <a class="item" href="{% url 'estante:cadastro-livro' %}">Cadastrar Livro</a>
            <a class="item" href="{% url 'estante:lista_livros' %}">Consultar</a>
            <!--<a class="item" href="#">Empréstimo</a>-->
            <a class="item" href="{% url 'estante:cadastro-pessoa' %}">Cadastrar Usuário</a>
            <a class="item" href="{% url 'estante:perfil' %}">Meu Perfil</a>
            <a class="item" href="{% url 'estante:logout' %}">Sair</a>
        {% else %}
            <a class="item" href="{% url 'estante:cadastro-pessoa' %}">Cadastre-se</a>
        {% endif %}

    </div>

</header>


<body>
<article class="ui container">
    {% block content %}
    {% endblock content %}
</article>
</body>

estante/templates/cad_livro.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        {% if id == None %}
            <h1>Cadastro de Livro</h1>
        {% else %}
            <h1>Edição de Livro</h1>
        {% endif %}

        <section class="ui container">
            <article class="ui grid">
                <div class="two wide column"></div>
                <div class="twelve wide column" id="margem">

                    {% if msg %}
                        {{ msg }}
                    {% endif %}

                    {% if id == None %}
                        <form method="POST" action="{% url 'estante:cadastro-livro' %}" class='ui fluid form'>
                    {% else %}
                        <form method="POST" action="{% url 'estante:edita-livro' id %}" class='ui fluid form'>
                    {% endif %}
                    {% csrf_token %}

                    <label>{{ form.id_livro.label }}</label>
                    {{ form.id_livro }}
                    {% if form.id_livro.errors %}
                        {{ form.id_livro.errors }}
                    {% endif %}<br/>

                    <label>{{ form.titulo.label }}</label>
                    {{ form.titulo }}
                    {% if form.titulo.errors %}
                        {{ form.titulo.errors }}
                    {% endif %}<br/>

                    <label>{{ form.autor.label }}</label>
                    {{ form.autor }}
                    {% if form.autor.errors %}
                        {{ form.autor.errors }}
                    {% endif %}<br/>

                    <label>{{ form.editora.label }}</label>
                    {{ form.editora }}
                    {% if form.editora.errors %}
                        {{ form.editora.errors }}
                    {% endif %}<br/>

                    <label>{{ form.ano.label }}</label>
                    {{ form.ano }}
                    {% if form.ano.errors %}
                        {{ form.ano.errors }}
                    {% endif %}<br/>

                    <button type="submit" class="ui verde button">Salvar</button>
                    <br>
                    <a href="{% url 'estante:perfil' %}">Voltar ao perfil</a>
                    </form>
                </div>
            </article>
        </section>
    {% else %}
        <h4>Você não esta logado no sistema</h4>
        <a href="{% url 'estante:login' %}">Login</a><br/>
    {% endif %}

{% endblock content %}

estante/templates/cad_pessoa.html
{% extends 'base.html' %}
{% block content %}

    <h1>
        Cadastrar Usuário
    </h1>

    <section class="ui container">
        <article class="ui grid">
            <div class="two wide column"></div>
            <div class="twelve wide column" id="margem">
                <form method="POST" action="{% url 'estante:cadastro-pessoa' %}" class='ui fluid form'>

                    {% csrf_token %}

                    {% if msg %}
                        <div>{{ msg }}</div>
                    {% endif %}

                    {% if form.username %}
                        <label>{{ form.username.label }}</label>
                        {{ form.username }} <br/>
                        {% if form.username.errors %}
                            {{ form.username.errors }}
                        {% endif %}
                    {% endif %}

                    <label>{{ form.password.label }}</label>
                    {{ form.password }} <br/>
                    {% if form.password.errors %}
                        {{ form.password.errors }}
                    {% endif %}


                    <label>{{ form.first_name.label }}</label>
                    {{ form.first_name }} <br/>
                    {% if form.first_name.errors %}
                        {{ form.first_name.errors }}
                    {% endif %}


                    <label>{{ form.last_name.label }}</label>
                    {{ form.last_name }} <br/>
                    {% if form.last_name.errors %}
                        {{ form.last_name.errors }}
                    {% endif %}


                    <label>{{ form.cpf.label }}</label>
                    {{ form.cpf }} <br/>
                    {% if form.cpf.errors %}
                        {{ form.cpf.errors }}
                    {% endif %}



                    <label>{{ form.telefone.label }}</label>
                    {{ form.telefone }} <br/>
                    {% if form.telefone.errors %}
                        {{ form.telefone.errors }}
                    {% endif %}


                    <label>{{ form.email.label }}</label>
                    {{ form.email }} <br/>
                    {% if form.email.errors %}
                        {{ form.email.errors }}
                    {% endif %}


                    <label>{{ form.endereco.label }}</label>
                    {{ form.endereco }} <br/>
                    {% if form.endereco.errors %}
                        {{ form.endereco.errors }}
                    {% endif %}
                    <div align="center">

                        <button type="submit" class="ui verde button">Salvar</button>
                    </div>
                </form>
                {% if user.is_authenticated %}
                    <a href="{% url 'estante:perfil' %}">Voltar</a>
                {% else %}
                    <a href="{% url 'estante:login' %}">Voltar</a>
                {% endif %}

            </div>
        </article>
    </section>

{% endblock content %}

estante/templates/lista_livros.html
{% extends 'base.html' %}
{% block content %}
    <h1>
        Listagem de Livros
    </h1>

    <section class="ui container">
        <article class="ui grid">
            <div class="two wide column"></div>
            <div class="twelve wide column" id="margem">
    {% if user.is_authenticated %}
        <h4>Meus livros</h4>
            {% for livro in livros %}
                {% ifequal user.id livro.dono.id %}
                    Título: <a href="{% url 'estante:perfil_livro' livro.id %}">{{ livro.titulo }}</a><br/>
                {% endifequal %}
            {%endfor %}
        {% if emprestimos %}
        <h4>Livros Emprestados</h4>

            {% for emprestimo in emprestimos %}
                {% if emprestimo.pegou_emprestado_id == user.id %}
                    <a href="{% url 'estante:perfil_livro' emprestimo.livro_emprestado_id %}">{{ emprestimo.livro_emprestado.titulo }}</a><br/>
                {% endif %}
            {%endfor %}
        {% endif %}
        <br/>
        <div>
            <h4>Procurar livro</h4>
                <form method="POST" action="{% url 'estante:procurar_livro' %}" class='ui form'>
                {% csrf_token %}

                {% if msg %}
                    <div>{{ msg }}</div>
                {% endif %}
                <select name = 'tipo' style="width: 100px">
                    <option value ='titulo'>Título</option>
                    <option value ='autor'>Autor</option>
                    <option value ='dono'>Dono</option>
                </select>
                <input type="text" name="procura" onfocus="this.value='';" style="width: 400px"><br/><br/>
                <button type="submit" class="ui button">Pesquisa</button><br/>
            </form>
        </div>
    {% else %}
        <h4>Você não esta logado no sistema</h4>
        <a href="{% url 'estante:login' %}">Login</a><br/>
    {% endif %}
            </div>
        </article>
    </section>
{% endblock content %}

estante/templates/perfil_livro.html
{% extends 'base.html' %}
{% block content %}
    <section class="ui container">
        <article class="ui grid">
            <div class="two wide column"></div>
            <div class="twelve wide column" id="margem">
    {% if user.is_authenticated %}
        <h2> {{ livro.titulo }} </h2>
        <h5> Editora: {{ livro.editora }}</h5>
        <h5> Autor: {{ livro.autor }}</h5>
        <h5> Ano: {{ livro.ano }}</h5>
        <h5> Dono do livro: {{ livro.dono }}</h5>


        {% if livro.dono.id == user.id and not emprestimo%}
            {% if livro.status == True %}
                <h5>Status: Ativo</h5>
            {% endif %}
            {% if livro.status == False %}
                <h5>Status: Desativado</h5>
            {% endif %}

            <a href="{% url 'estante:edita-livro' livro.id %}">Editar</a><br/>
            <form method="POST" action="{% url 'estante:esconder_livro' livro.id %}" class='ui form'>
                <button type="submit" class="ui verde button">Mudar Status</button>
                {% csrf_token %}
            </form>
        {% endif %}

        {% if livro.dono.id != user.id %}
            {% if emprestimo.pegou_emprestado_id == user.id %}
               <a href="{% url 'estante:devolver_livro' emprestimo.id %}">Devolver</a>
            {% endif %}
            {% if not emprestimo and livro.status == True %}
                <a href="{% url 'estante:emprestimo' livro.id %}">Emprestar</a>
            {% endif %}
        {% endif %}

        <a href="{% url 'estante:lista_livros' %}">Voltar aos livros</a>
    {% else %}
        <h4>Você não esta logado no sistema</h4>
        <a href="{% url 'estante:login' %}">Login</a><br/>
    {% endif %}
    </div>
        </article>
    </section>
{% endblock content %}

estante/templates/procurar_livro.html
{% extends 'base.html' %}
{% block content %}
    <section class="ui container">
        <article class="ui grid">
            <div class="two wide column"></div>
            <div class="twelve wide column" id="margem">
    {% if user.is_authenticated %}
        <h3>{{ msg }}</h3><br/>
    {% if tipo_lista == "dicionario" %}
    {% for dono_id, livros in livros.items %}
            {% for livro in livros %}
                <a href="{% url 'estante:perfil_livro' livro.id %}">Título: {{ livro.titulo }}</a><br>
                Autor: {{ livro.autor }} <br/>
                Dono : {{ livro.dono }} <br/>
                <br/>
            {% endfor %}
        {% endfor %}

    {% else %}
        {% for livro in livros %}
            {% if livro.status == True and livro.dono.is_active == True %}
                <a href="{% url 'estante:perfil_livro' livro.id %}">
                    Título: {{ livro.titulo }}</a><br>
                    Autor: {{ livro.autor }}<br>
                    Dono: {{ livro.dono  }}<br/>
                <br/>
            {% endif %}
        {% endfor %}
    {% endif %}

    <a href="{% url 'estante:lista_livros' %}">Voltar a sua biblioteca</a><br/>
    {% else %}
        <h4>Você não esta logado no sistema</h4>
        <a href="{% url 'estante:login' %}">Login</a><br/>
    {% endif %}
            </div>
        </article>
    </section>
{% endblock content %}